-- Insert landmarks from CSV
INSERT INTO pin (id, creatorID, latitude, longitude, title, address, description, image, likes) VALUES
(300, 46, 40.169328, -124.2271324, 'Lost Coast Trail', '3750 Lighthouse Rd, Petrolia, CA 95558, United States', 'Backpack California’s remote Lost Coast from the Mattole trailhead—wild beaches, tide-dependent headlands, and King Range scenery.', 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Lost%20Coast%20Trail%2001.jpg?width=1600', 75),
(301, 12, 34.1708578, -117.9332738, 'Fern Canyon', 'Gold Bluffs Beach Rd, Orick, CA 95555, United States', 'Walk through a lush, fern-draped slot canyon near Gold Bluffs Beach in Prairie Creek Redwoods State Park—expect creek crossings in-season.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fern%20canyon%207x10.jpg?width=1600', 91),
(302, 37, 41.17556, -122.33944, 'Castle Crags Dome Trail', '20022 Castle Creek Rd, Castella, CA 96017, United States', 'Steep, rewarding hike to Castle Dome viewpoints in Castle Crags State Park, with big granite formations and Mount Shasta vistas.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Castle%20Dome%20and%20Mount%20Shasta.jpg?width=1600', 24),
(303, 43, 40.4532818, -121.4940683, 'Bumpass Hell Trail', 'Lassen Volcanic National Park Hwy, Mineral, CA 96063, United States', 'Classic Lassen hike to the park’s largest hydrothermal basin—boiling pools, fumaroles, and boardwalk overlooks (seasonal access varies).', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bumpass%20Hell%2C%20Lassen%20Volcanic%20National%20Park%2C%20California%20(23237985341).jpg?width=1600', 59),
(304, 14, 39.6261391, -121.2683679, 'Feather Falls Trail', 'Roseben Ave, Oroville, CA 95966, United States', 'Forest hike to one of California’s tallest waterfalls—Feather Falls plunges dramatically into a rugged canyon (hot in summer).', 'https://commons.wikimedia.org/wiki/Special:FilePath/Feather%20falls%20plumas%20national%20forest.jpg?width=1600', 32),
(305, 18, 37.9537367, -122.7833527, 'Alamere Falls', 'Mesa Rd, Bolinas, CA 94924, United States', 'Iconic Point Reyes trek from the Palomarin trailhead to a rare tidefall where Alamere Creek drops onto the beach (stay on official routes).', 'https://commons.wikimedia.org/wiki/Special:FilePath/Top%20of%20Alamere%20Falls.jpg?width=1600', 93),
(306, 26, 37.93184, -122.63539, 'Cataract Falls Trail', 'Bolinas-Fairfax Rd, Fairfax, CA 94930, United States', 'Marin County favorite featuring a series of cascades on Cataract Creek—best after winter rains and during spring flow.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cataract%20Falls%2C%20Mount%20Tamalpais%20Watershed.jpg?width=1600', 86),
(307, 21, 37.429725, -122.3371513, 'Purisima Creek Redwoods', '13130 Skyline Blvd, Woodside, CA 94062, United States', 'Redwood canyon hiking in the Santa Cruz Mountains with ferny creek corridors and occasional coastal views from ridgeline trails.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Purisima%20Creek%20vista.jpg?width=1600', 18),
(308, 23, 36.0873537, -121.5946174, 'Boronda Trail', 'CA-1, Big Sur, CA 93920, United States', 'Very steep Big Sur climb into the Ventana Wilderness via Boronda Ridge, rewarding hikers with dramatic coastal and Santa Lucia Range views.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ventana%20wilderness.jpg?width=1600', 15),
(309, 26, 35.81542, -121.35915, 'Salmon Creek Falls Trail', 'CA-1, Big Sur, CA 93920, United States', 'A short, sweet hike off Highway 1 to a mossy coastal waterfall in the Silver Peak Wilderness area.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salmon%20Creek%20(Big%20Sur)%20-%20panoramio.jpg', 50),
(310, 36, 35.2728, -120.8887, 'Montaña de Oro Bluff Trail', '3550 Pecho Valley Rd, Los Osos, CA 93402, United States', 'Coastal bluff-top walking with nonstop ocean views, rugged cliffs, and access to beaches and tidepools.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Montana%20de%20Oro%20State%20Park%20-%20panoramio%20(1).jpg', 49),
(311, 15, 34.28306, -117.74667, 'Bridge to Nowhere Hike', 'East Fork Rd, Azusa, CA 91702, United States', 'A classic river hike with multiple stream crossings that ends at the famous “Bridge to Nowhere” in the San Gabriel Mountains.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bridge%20to%20Nowhere%20-%20San%20Gabriel%20River.jpg', 100),
(312, 16, 33.7034924, -116.2269696, 'Painted Canyon', 'Painted Canyon Rd, Mecca, CA 92254, United States', 'A colorful desert slot-and-ladder style canyon route with sculpted walls and an adventurous feel near Mecca.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Painted%20Canyon%20Mecca%20California.jpg', 17),
(313, 24, 33.76609, -117.67915, 'Black Star Canyon Trail', '13333 Black Star Canyon Rd, Silverado, CA 92676, United States', 'A stream-crossing canyon hike in the Santa Ana Mountains that leads toward seasonal falls and shaded riparian scenery.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Black%20Star%20Canyon%20-%20panoramio.jpg', 96),
(314, 20, 33.1824871, -116.2154463, 'The Slot', 'Borrego Mountain Wash, Borrego Springs, CA 92004, United States', 'A fun, family-friendly slot canyon adventure with tight walls and sandy washes in Anza-Borrego Desert State Park.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Anza-Borrego%20Desert%20State%20Park%20Slot%20Canyon.jpg', 0),
(315, 31, 37.13215, -118.50927, 'Big Pine Lakes Trail', 'Glacier Lodge Rd, Big Pine, CA 93513, United States', 'A stunning alpine trek to a chain of turquoise lakes beneath the Palisades, with classic Eastern Sierra views.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Big%20Pine%20Lakes%20-%20John%20Muir%20Wilderness.jpg', 28),
(316, 35, 37.9295411, -119.045671, 'Panum Crater', '1 Visitor Center Dr, Lee Vining, CA 93541, United States', 'An easy volcanic loop that lets you walk the rim and into the crater with wide-open views of Mono Lake and the Sierra.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Panum%20Crater%20Mono%20Basin.jpg', 97),
(317, 45, 34.4398008, -119.0805579, 'Santa Paula Canyon', '17001 Santa Paula St, Santa Paula, CA 93060, United States', 'A creekside canyon hike to the famous Punch Bowls—clear pools and cascades perfect for a warm-day adventure.', 'https://ropewiki.com/images/0/03/Santa_Paula_Creek_pic1.jpg', 93),
(318, 39, 32.9899492, -116.7296427, 'Cedar Creek Falls', '15519 Thornbush Rd, Ramona, CA 92065, United States', 'A permit-managed San Diego classic featuring a rugged gorge hike to a tall waterfall and swimming hole (seasonal).', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cleveland%20National%20Forest%20-%20Social%206.jpg', 23),
(319, 6, 34.9341862, -115.7196087, 'Kelso Dunes', 'Kelso-Dunes Rd, Baker, CA 92309, United States', 'A leg-burning but rewarding climb up “singing” sand dunes with sweeping Mojave National Preserve panoramas.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kelso%20Dunes%20Mojave%20National%20Preserve.jpg', 9),
(320, 36, 41.7783561, -124.1315808, 'Boy Scout Tree Trail', 'Howland Hill Rd, Crescent City, CA 95531, United States', 'A serene redwood forest hike to massive old-growth giants in Jedediah Smith Redwoods State Park.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jedediah%20Smith%20Redwoods%20State%20Park%20-%20Howland%20Hill%20Road.jpg', 63),
(321, 10, 39.61041, -121.56063, 'Table Mountain “Phantom Falls”', '2488 Cherokee Rd, Oroville, CA 95965, United States', 'A seasonal spring spectacle: wildflower-covered tablelands leading to the dramatic (and often fleeting) Phantom Falls.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Phantom%20Falls%20North%20Table%20Mountain.jpg', 27),
(322, 37, 34.3394243, -117.177035, 'Deep Creek Hot Springs', '6100 Bowen Ranch Rd, Apple Valley, CA 92308, United States', 'A challenging out-and-back trek to natural riverside hot spring pools in the San Bernardino National Forest area.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Deep%20Creek%20Hot%20Springs%20-%20San%20Bernardino%20National%20Forest.jpg', 68),
(323, 25, 34.0440713, -118.7556101, 'Solstice Canyon', '3455 Solstice Canyon Rd, Malibu, CA 90265, United States', 'An easy-to-moderate Malibu canyon ramble with ruins, creek crossings, and lush coastal foothill scenery.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Solstice%20Canyon%20Malibu.jpg', 42),
(324, 34, 36.4895798, -121.1972548, 'High Peaks Trail', '5000 CA-146, Paicines, CA 95043, United States', 'Pinnacles’ signature route through dramatic spires and airy ridgelines—big views and condor country.', 'https://commons.wikimedia.org/wiki/Special:FilePath/High%20Peaks%20of%20Pinnacles.JPG', 24),
(325, 4, 40.8197249, -124.1816255, 'Samoa Cookhouse', '908 Vance Ave, Samoa, CA 95564, United States', 'A historic, family-style lumber-camp cookhouse serving hearty classics in a truly one-of-a-kind setting.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Samoa%20Cookhouse%20Samoa%20CA.jpg', 63),
(326, 25, 32.7471357, -117.2512075, 'Hodad’s', '5010 Newport Ave, San Diego, CA 92107, United States', 'Ocean Beach’s iconic burger stop—loud, fun, and famously stacked with locals-and-visitors energy.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hodad%27s%20Ocean%20Beach%20Dec%202015.jpg', 3),
(327, 15, 34.42, -119.698, 'La Super-Rica Taqueria', '622 N Milpas St, Santa Barbara, CA 93103, United States', 'A Santa Barbara legend known for no-frills, flavor-packed tacos and a line that moves fast (most days).', 'https://ladyducayne.com/wp-content/uploads/2021/11/la-super-rica-taqueria-santa-barbara-exterior.jpg', 97),
(328, 21, 34.0081414, -118.4144703, 'Tito’s Tacos', '11222 Washington Pl, Culver City, CA 90230, United States', 'A longtime LA institution—classic crunchy tacos, a bustling counter line, and serious nostalgia factor.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tito%27s%20Tacos%20exterior.jpg', 12),
(329, 37, 37.2520672, -122.3827841, 'Duarte’s Tavern', '202 Stage Rd, Pescadero, CA 94060, United States', 'A beloved coastside tavern famous for comforting plates, old-school charm, and legendary pies.', 'https://www.duartestavern.com/wp-content/uploads/2020/01/Duartes-Tavern-Exterior.jpg', 35),
(330, 24, 33.1188418, -117.0852029, 'Cafe 222', '222 Island Ave, San Diego, CA 92101, United States', 'Downtown San Diego breakfast staple known for creative waffles and a cozy, long-running neighborhood vibe.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/9b/8b/c7/cafe-222.jpg', 73),
(331, 41, 36.2218116, -121.7596565, 'Nepenthe', '48510 CA-1, Big Sur, CA 93920, United States', 'A bucket-list Big Sur stop with dramatic ocean views, cliffside patios, and sunset-worthy scenery.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nepenthe%20Big%20Sur%20California.jpg', 88),
(332, 15, 33.803, -117.853, 'Brew Hawg BBQ & Root Beer', '665 N Tustin St Ste J, Orange, CA 92867, United States', 'A casual Orange spot serving BBQ plates and house root beer—easygoing counter service and big comfort flavors.', 'https://www.brewhawg.com/uploads/1/3/7/6/137602455/editor/brew-hawg-storefront.jpg', 32),
(333, 10, 38.663, -120.987, 'China City Restaurant', '4100 Cameron Park Dr Ste 114, Cameron Park, CA 95682, United States', 'A go-to neighborhood Chinese restaurant in Cameron Park with familiar favorites and generous portions.', 'https://s3-media0.fl.yelpcdn.com/bphoto/qorgVHqjDw7KMB1Pn8YrPg/o.jpg', 4),
(334, 44, 34.0596738, -118.236941, 'Philippe The Original', '1001 N Alameda St, Los Angeles, CA 90012', 'Historic deli operating since 1908, famous for sawdust floors and inventing the French Dipped Sandwich.', 'https://images.pexels.com/photos/2983099/pexels-photo-2983099.jpeg', 19),
(335, 44, 38.6409825, -121.5034177, 'India Oven', '3511 Truxel Rd, Sacramento, CA 95834', 'Highly-rated Indian cuisine offering authentic curries and tandoori dishes in Sacramento.', 'https://images.pexels.com/photos/12737917/pexels-photo-12737917.jpeg', 15),
(336, 44, 38.151656, -122.888099, 'The Marshall Store', '19225 State Route 1, Marshall, CA 94940', 'Rustic oyster bar on Tomales Bay serving fresh local seafood and smoked meats.', 'https://images.pexels.com/photos/566345/pexels-photo-566345.jpeg', 12),
(337, 44, 38.4682055, -123.0125555, 'Lightwave Coffee & Kitchen', '9725 Main St, Monte Rio, CA 95462', 'Cozy cafe in the Russian River area offering artisanal coffee and fresh pastries.', 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg', 8),
(338, 44, 37.7836966, -122.4173873, 'Outta Sight Pizza', '422 Larkin St, San Francisco, CA 94102', 'Popular slice shop in the Tenderloin known for its thin, crispy New York-style pizza.', 'https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg', 22),
(339, 44, 37.8718992, -122.2713563, 'Rose Pizzeria', '1960 University Ave, Berkeley, CA 94704', 'Berkeley spot featuring thin-crust pizzas and natural wines in a patio setting.', 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg', 18),
(340, 44, 37.8009277, -122.2738733, 'Popoca', '906 Washington St, Oakland, CA 94607', 'Oakland eatery specializing in authentic Salvadoran cuisine prepared over a wood fire.', 'https://images.pexels.com/photos/2725744/pexels-photo-2725744.jpeg', 14),
(341, 44, 34.090623, -118.275466, 'Spoon & Pork', '3131 W Sunset Blvd, Los Angeles, CA 90026', 'Michelin-recommended modern Filipino comfort food in the heart of Silver Lake.', 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', 25),
(342, 44, 34.077227, -118.264223, 'Elf Cafe', '2135 W Sunset Blvd, Los Angeles, CA 90026', 'Intimate vegetarian Mediterranean restaurant in Echo Park featuring natural wines.', 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', 20),
(343, 44, 34.090954, -118.337227, 'Calabama', '6751 Santa Monica Blvd, Los Angeles, CA 90038', 'Southern-style breakfast sandwich spot known for its biscuits and hot sauce.', 'https://images.pexels.com/photos/4958792/pexels-photo-4958792.jpeg', 17),
(344, 44, 34.114666, -118.780449, 'The Old Place', '29983 Mulholland Hwy, Agoura Hills, CA 91301', 'Historic, rustic steakhouse in the Santa Monica Mountains serving food cooked over oak.', 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg', 28),
(345, 44, 33.828135, -118.115386, 'Appu''s Cafe', '3816 Woodruff Ave Suite 100B, Long Beach, CA 90808', 'Fusion cafe serving healthy Indian and Mexican vegetarian dishes in a medical building.', 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg', 13),
(346, 44, 32.7018225, -117.1451475, 'Las Cuatro Milpas', '1857 Logan Ave, San Diego, CA 92113', 'Legendary cash-only Barrio Logan staple serving authentic Mexican tortillas and chorizo since 1933.', 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg', 30),
(347, 44, 41.541333, -124.095033, 'Klamath River Overlook', 'Requa Rd, Klamath, CA 95548', 'Scenic overlook offering panoramic views of the Klamath River mouth meeting the Pacific Ocean.', 'https://images.pexels.com/photos/1450360/pexels-photo-1450360.jpeg', 22),
(348, 44, 39.452667, -123.813386, 'Glass Beach', 'W Elm St & Glass Beach Dr, Fort Bragg, CA 95437', 'Famous beach covered in colorful sea glass created from years of refuse dumping.', 'https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg', 45),
(349, 44, 37.928818, -122.578619, 'Mount Tamalpais East Peak', 'Old Railroad Grade Trail, Mill Valley, CA 94941', 'Summit offering sweeping views of the Bay Area, accessible via hiking trails or drive.', 'https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg', 33),
(350, 44, 37.881591, -121.914215, 'Mount Diablo Summit', 'Summit Rd, Walnut Creek, CA 94598', 'Highest peak in the East Bay, offering views of the Sierras and Golden Gate Bridge on clear days.', 'https://images.pexels.com/photos/1933239/pexels-photo-1933239.jpeg', 29),
(351, 44, 35.372958, -117.990694, 'Red Rock Canyon State Park', '37749 Abbott Dr, Cantil, CA 93519', 'Desert park featuring spectacular rock formations and scenic desert cliffs.', 'https://images.pexels.com/photos/1619299/pexels-photo-1619299.jpeg', 18),
(352, 44, 33.304205, -116.239066, 'Font''s Point', 'Font''s Point, Borrego Springs, CA 92004', 'The most popular viewpoint in Anza-Borrego, overlooking the dramatic Borrego Badlands.', 'https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg', 21),
(353, 44, 35.6175, -117.3683, 'Trona Pinnacles', 'Pinnacles Rd, Trona, CA 93562', 'Unique geological features in the California Desert Conservation Area, consisting of over 500 tufa spires.', 'https://images.pexels.com/photos/1770809/pexels-photo-1770809.jpeg', 24),
(354, 44, 36.6114, -118.1248, 'Mobius Arch', 'Movie Flat Rd, Lone Pine, CA 93545', 'Famous rock arch in the Alabama Hills that frames Mount Whitney perfectly.', 'https://images.pexels.com/photos/2166711/pexels-photo-2166711.jpeg', 31),
(355, 44, 37.9438, -119.0306, 'Mono Lake South Tufa', 'Test Station Rd, Lee Vining, CA 93541', 'Limestone tufa towers rising from the alkaline waters of Mono Lake.', 'https://images.pexels.com/photos/1268362/pexels-photo-1268362.jpeg', 35),
(356, 44, 34.5572, -115.7814, 'Amboy Crater', 'Crater Rd, Amboy, CA 92304', 'Extinct cinder cone volcano located in the Mojave Desert along Route 66.', 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg', 16),
(357, 44, 37.0053, -121.9959, 'Top of the World', '855 Branciforte Dr, Santa Cruz, CA 95065', 'Famous disc golf hole and viewpoint at DeLaveaga Park overlooking Santa Cruz.', 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg', 14),
(358, 44, 33.7423, -118.4107, 'Point Vicente Bluffs', '31550 Palos Verdes Dr W, Rancho Palos Verdes, CA 90275', 'Scenic coastal reserve with a lighthouse, offering prime whale watching opportunities.', 'https://images.pexels.com/photos/1268871/pexels-photo-1268871.jpeg', 23),
(359, 44, 32.7235, -117.2587, 'Sunset Cliffs', '705 Cornish Dr, San Diego, CA 92107', 'Dramatic sandstone cliffs bordering the ocean, popular for sunset viewing and surfing.', 'https://images.pexels.com/photos/1631665/pexels-photo-1631665.jpeg', 40),
(360, 44, 32.8899, -117.2533, 'Torrey Pines Gliderport', '2800 Torrey Pines Scenic Dr, La Jolla, CA 92037', 'Historic aviation site on coastal cliffs, used for paragliding and hang gliding.', 'https://images.pexels.com/photos/1654506/pexels-photo-1654506.jpeg', 27),
(361, 44, 34.0016, -118.8067, 'Point Dume', 'Cliffside Dr & Birdview Ave, Malibu, CA 90265', 'Prominent headland in Malibu featuring cliffs, beaches, and whale watching trails.', 'https://images.pexels.com/photos/1666021/pexels-photo-1666021.jpeg', 32),

INSERT INTO pin (id, creatorID, latitude, longitude, title, address, description, image, likes) VALUES

(302, 8, 35.86965, 138.74018, 'Nishizawa Gorge', 'Yamanashi City, Yamanashi Prefecture, Japan', 'A stunning river gorge known for its crystal-clear streams and a series of captivating waterfalls (including the five-tiered Nanatsugama Godan Falls) amid lush primeval forests. A gentle riverside trail offers “forest bathing” tranquility and spectacular scenery through all seasons.', NULL, 0),

(303, 5, 34.56669, 136.08252, 'Akame 48 Waterfalls', 'Nabari, Mie Prefecture, Japan', 'A mystical 4km hiking trail through a forested valley dotted with countless waterfalls and pools, once a secret training ground for Iga ninja. Visitors can enjoy mossy paths, cascading falls, and even spot giant salamanders in this serene quasi-national park.', NULL, 0),

(304, 12, 40.62636, 140.95469, 'Oirase Gorge', 'Towada, Aomori Prefecture, Japan', 'A breathtaking 14-kilometer river valley winding from Lake Towada through dense woods, featuring dozens of cascades and rapids amid verdant mossy boulders. A well-maintained trail and road follow the crystal-clear Oirase Stream, making it a paradise for hikers and photographers especially during autumn foliage.', NULL, 0),

(305, 16, 38.70064, 140.02970, 'Dewa Sanzan (Three Mountains of Dewa)', 'Tsuruoka, Yamagata Prefecture, Japan', 'An ancient pilgrimage route over three sacred peaks (Haguro, Gassan, Yudono) representing past, present, and future in mountain asceticism. Pilgrims (yamabushi) climb stone paths through towering cedars and venerable shrines seeking spiritual rebirth, often staying in shukubo lodges serving ascetic vegan cuisine.', NULL, 0),

(306, 23, 34.20891, 136.29531, 'Kumano Kodo Iseji Trail', 'Kumano Region, Mie Prefecture, Japan', 'A lesser-traveled branch of the Kumano Kodo pilgrimage linking Ise Grand Shrine to the three Kumano shrines in Wakayama. This historic 170-km route winds through coastal villages, bamboo forests, and steep stone paths. Pilgrims experience rural Japan, ancient tea houses, and stone lantern-lined passes as they journey toward spiritual fulfillment. (UNESCO World Heritage)', NULL, 0),

(307, 42, 36.36020, 138.64736, 'Usui Pass Railway Trail (Abt Road)', 'Karuizawa, Nagano – Annaka, Gunma, Japan', 'An abandoned Meiji-era mountain railway converted into a hiking trail, featuring eerie brick tunnels and towering bridge ruins through lush highland forest. Hikers pass the famous Maruyama Substation and the old Usui Pass train tracks, sometimes greeted by wild monkeys on this unique blend of history and nature.', NULL, 0),

(308, 8, 33.87360, 133.83623, 'Iya Kazurabashi (Vine Bridge)', 'Miyoshi, Tokushima Prefecture, Japan', 'A swaying footbridge woven from mountain vines spans the emerald Iyagawa River in a remote gorge of Shikoku. One of the few remaining vine bridges of Iya Valley, it was once used by fleeing clansmen and offers brave visitors a thrilling crossing 14 meters above the water, with scenic waterfalls and steep forested cliffs surrounding this rustic engineering marvel.', , 0),

(309, 15, 34.61488, 132.25169, 'Sandankyo Gorge', 'Akiota, Hiroshima Prefecture, Japan', 'A hidden five-tiered ravine stretching 13 kilometers of unspoiled beauty: emerald green waters, dramatic cliffs, and waterfalls including the three-tiered Sandan Falls that give the gorge its name. Visitors can hike shaded riverside trails, take a short boat ride to explore deeper sections of the gorge, and enjoy autumn colors reflecting on the canyon waters in this tranquil nature escape.', NULL, 0),

(310, 5, 40.51704, 140.15233, 'Shirakami Sanchi', 'Aomori–Akita Prefecture border, Japan', 'A vast UNESCO World Heritage virgin beech forest range preserving one of the last primeval ecosystems in Japan. Home to hidden waterfalls (like Anmon Falls), mountain streams, and abundant wildlife, Shirakami Sanchi offers seasoned hikers secluded trails through dense greenery and mossy gorges. This untouched wilderness invites quiet contemplation and strictly limits access to protect its fragile environment.', NULL, 0),

(311, 12, 30.33523, 130.52880, 'Yakushima Ancient Forest', 'Kagoshima Prefecture (Yakushima Island), Japan', 'A mystical island of ancient cedar forests where some yakusugi trees are over 1,000 years old. Trails like Shiratani Unsuikyo inspire scenes from Princess Mononoke with misty, moss-covered trunks, while the challenging trek to Jōmon Sugi (Japan’s oldest tree ~2,000 years) rewards hikers with primeval scenery. Lush and rainy, Yakushima’s ecosystem harbors endemic deer, monkeys, and waterfalls at every turn.', NULL, 0),

(312, 23, 39.95111, 140.82027, 'Mount Hachimantai Highlands', 'Hachimantai, Iwate/Akita Prefecture, Japan', 'A sprawling alpine plateau straddling Iwate and Akita, famed for its otherworldly volcanic landscapes and seasonal beauty. Gentle trails lead past mirror-like marsh ponds, fumaroles, and fields of alpine flowers. In autumn the area blazes with red and gold foliage, and in late spring the melting snow creates the “Dragon Eye” pattern on Kagami-numa pond, delighting nature lovers.', NULL, 0),

(313, 46, 45.17869, 141.24233, 'Mount Rishiri (Rishiri Island)', 'Rishirifuji, Hokkaido, Japan', 'A dormant volcano rising conically from the sea, often called “Rishiri-Fuji” for its elegant shape. This challenging 1,721m hike takes you through wildflower meadows and windswept pine forests to a panoramic summit with 360° views of the Sea of Japan and nearby Rebun Island. The unspoiled island atmosphere, without any mainland crowds, makes the trek especially rewarding for seasoned hikers seeking solitude.', NULL, 0),

(314, 46, 45.30603, 141.03812, 'Rebun Island Flower Trails', 'Rebun, Hokkaido, Japan', 'An island at Japan’s northern tip famed for its high latitude wildflowers and rolling coastal moorlands. In summer, gentle trekking paths like the Momoiwa Course are carpeted with over 300 varieties of flowers, some endemic to Rebun. Hikers enjoy sweeping sea views from green bluffs, quiet fishing hamlets, and maybe even a glimpse of Russia’s Sakhalin on clear days—all in a place often called the “Floating Island of Flowers.”', NULL, 0),

(315, 15, 43.30694, 140.36351, 'Cape Kamui', 'Shakotan Peninsula, Hokkaido, Japan', 'A dramatic promontory jutting into the Sea of Japan, offering a windswept 2.5km trail along cliffs to a lighthouse at the tip. Surrounded by astonishingly blue “Shakotan Blue” waters, Cape Kamui provides endless ocean panoramas and sheer drop-offs to crashing waves. Local lore forbade women from entering in ancient times; today all can enjoy its raw beauty, but visitors are urged to stay on the path for safety and conservation.', NULL, 0),

(316, 8, 33.59193, 135.95134, 'Kamikura-jinja Shrine', 'Shingu, Wakayama Prefecture, Japan', 'A small, ancient mountainside shrine perched under a huge sacred boulder (Gotobiki-iwa) overlooking Shingu city and the Pacific Ocean. Reached by climbing over 500 steep stone steps, the shrine marks the spot where Shinto deities descended according to legend. Intrepid visitors who ascend are rewarded with sweeping coastal views and a palpable sense of reverence at this power spot—especially during the annual Oto Matsuri fire festival.', NULL, 0),

(317, 46, 35.61240, 139.64553, 'Todoroki Valley Park', 'Setagaya, Tokyo, Japan', 'A surprising oasis of greenery and calm in suburban Tokyo. A short walking trail follows a babbling Yazawa River stream through a lush, tree-lined ravine, passing over small bridges and even by a hidden waterfall and cave tombs. The temperature here stays cooler—a refuge from city heat—making this little valley a favorite for locals seeking nature without leaving the metropolis.', NULL, 0),

(318, 12, 36.77341, 137.55850, 'Kurobe Gorge', 'Kurobe, Toyama Prefecture, Japan', 'A remote, V-shaped canyon carved by the Kurobe River, accessible via a charming retro diesel sightseeing train that chugs through 41 tunnels and over 20 bridges. The gorge offers untamed landscapes of sheer rock walls, emerald river pools, and natural hot spring spots like Kuronagi Onsen only reachable on foot. Particularly stunning in autumn when dense forests explode in color, this gorge exemplifies raw Hokuriku highland beauty.', NULL, 0),

(319, 5, 35.73342, 138.56827, 'Shosenkyo Gorge', 'Kofu, Yamanashi Prefecture, Japan', 'Often acclaimed as one of Japan’s most beautiful gorges, Shosenkyo features a dramatic granite canyon along the Arakawa River. An easy path showcases sights like the 30m Sengataki waterfall, towering cliffs and uniquely eroded rock formations (one resembles a huge jagged umbrella). Tea houses and craft shops dot the trail’s end. Especially popular in autumn for its brilliant maples, the gorge remains relatively uncrowded on weekdays.', NULL, 0),

(320, 15, 33.77170, 133.12030, 'Mt. Ishizuchi', 'Saijo, Ehime Prefecture, Japan', 'Western Japan’s tallest peak (1,982m) and a sacred mountain in Shugendō practice. The steep summit approach features thrilling iron chains that climbers can use to ascend near-vertical rock faces (with alternate routes provided). At the top, a small shrine and panoramic views of the Seto Inland Sea await. Pilgrims clad in white and hearty hikers alike scale Ishizuchi during the summer open season, earning bragging rights on this iconic Shikoku peak.', NULL, 0),

(321, 46, 35.14827, 135.76894, 'Kurama to Kibune Hike', 'Kyoto, Kyoto Prefecture, Japan', 'A gentle 1.5–2 hour hike connects two picturesque villages in the northern hills of Kyoto. Starting at Kurama-dera (a mountainside temple known for its tengu goblin legends) and ending at the Kibune Shrine, the trail passes under tall cedars and past small wayshrines. After the trek, hikers often relax by Kibune’s riverside restaurants with kawadoko platforms over flowing water in summer—a refreshing reward from the spiritual stroll.', NULL, 0),

(322, 5, 36.93833, 139.21944, 'Oze National Park', 'Gunma/Fukushima/Tochigi Prefecture, Japan', 'A high-altitude marshland and pond-filled valley ringed by mountains, famous for its skunk cabbage blooms in spring and golden grasslands in autumn. Well-maintained wooden boardwalks guide visitors across the peat bogs of Ozegahara and around Lake Ozenuma, protecting the fragile ecosystem. No private vehicles are allowed; hikers come by bus and often overnight in mountain huts. The expansive sky, clear air, and reflective waters make Oze feel like a world apart.', NULL, 0),

(323, 23, 34.50111, 131.30472, 'Akiyoshidō Cave', 'Mine, Yamaguchi Prefecture, Japan', 'One of Japan’s largest limestone caves, with an otherworldly 1km public route through vast caverns lit to reveal stunning rock formations. Visitors walk beside an underground river and admire features like the “Hundred Plates” (terraced pools of mineral-rich water) and massive stalactites hanging from 80m-high ceilings. Above ground, the Akiyoshidai plateau is a karst landscape of rolling hills pockmarked with sinkholes – a stark contrast to the hidden world below.', NULL, 0),

(324, 46, 32.70835, 131.30805, 'Takachiho Gorge', 'Takachiho, Miyazaki Prefecture, Japan', 'A narrow chasm of sheer basalt cliffs draped in lush foliage, carved by the Gokase River. Tourists can rent a rowboat to paddle under the iconic 17m Manai Falls that cascade into the gorge, or stroll the paved cliff-edge path above for bird’s-eye views. Steeped in mythology (legend says the Sun Goddess hid here), Takachiho offers a cool, ethereal experience, especially when morning mist and sunlight combine to create magical lighting.', NULL, 0),

(325, 12, 45.52314, 141.94378, 'Cape Sōya', 'Wakkanai, Hokkaido, Japan', 'The northernmost tip of Japan’s main islands, marked by a simple monument and a windblown view across the sea toward Russia’s Sakhalin on clear days. This rugged coastal point has a lonely, edge-of-the-world atmosphere. Visitors often take commemorative photos at the monument and visit the small museum or the nearby “Songs of Soya” monument. Wild deer sometimes graze in the area. In summer, the midnight sun lingers; in winter, icy winds underscore its subarctic feel.', NULL, 0),

(326, 46, 26.50202, 127.85733, 'Cape Manzamo', 'Onna, Okinawa Prefecture, Japan', 'A famous grassy bluff on Okinawa’s western coast, ending in a dramatic cliff shaped like an elephant’s trunk over the turquoise East China Sea. Name meaning “field for 10,000 to sit” comes from its broad flat top. It’s a popular spot among locals for sunsets as the sun dips into the ocean horizon. The surrounding coral shoreline and clear waters also make it a prime area for snorkeling and diving (though the cape itself is for viewing only).', NULL, 0),

(327, 15, 24.33196, 123.85352, 'Iriomote Mangrove Forest', 'Taketomi (Iriomote), Okinawa Prefecture, Japan', 'A wild, largely untouched subtropical island (90% covered in dense jungle) known as “the Galápagos of Japan.” Adventurers can kayak through mangrove-lined rivers like the Urauchi, then trek to secluded waterfalls such as Pinaisara Falls. Endemic wildlife abounds (including the rare Iriomote wild cat). With minimal roads and only small villages, Iriomote offers a true off-grid nature immersion, best explored with local guides to navigate its rivers and rainforest.', NULL, 0),

(328, 46, 38.29533, 141.40346, 'Tashirojima (Cat Island)', 'Ishinomaki, Miyagi Prefecture, Japan', 'A small rural island in Miyagi Prefecture where cats significantly outnumber humans. Originally the felines were kept to control mice in silkworm farms, but now semi-feral cats freely roam the fishing villages, laze on harbor walls, and happily interact with visitors. There are cat-shaped cabins for tourists (the island embraces the cat theme wholeheartedly). Dogs are not allowed, to keep the peace among the feline residents. A paradise for cat lovers seeking a quirky day trip.', NULL, 0),

(329, 5, 38.04090, 140.53040, 'Zao Fox Village', 'Shiroishi, Miyagi Prefecture, Japan', 'A unique sanctuary in the mountains where over 100 free-roaming foxes live in a spacious fenced-in habitat. Visitors can walk designated paths observing and photographing foxes of various breeds lounging, playing, or begging for treats (which can be purchased on-site). While resembling a wild setting, it is essentially an open-air zoo focused on fox conservation. Guests are advised not to touch the foxes and to follow ethical guidelines (e.g., no outside food) to ensure the animals’ well-being.', NULL, 0),

(330, 46, 34.30830, 132.99350, 'Okunoshima (Rabbit Island)', 'Takehara (Okunoshima), Hiroshima, Japan', 'A small island in the Inland Sea infamous for its WWII poison gas factory, now overrun by hundreds of friendly feral rabbits. With no natural predators and feeding by tourists, the bunnies hop freely along paths and approach visitors eagerly for snacks. You can walk or cycle around the island (3km circumference) visiting war ruins and a little museum, but the main draw is the surreal sight of rabbits grazing on lawns and crowding around anyone rustling a bag of vegetables.', , 0),

(331, 12, 32.46667, 139.76667, 'Aogashima Volcano Island', 'Philippine Sea (Tokyo Admin), Japan', 'A remote, oval-shaped volcanic island south of Tokyo, home to ~170 residents living inside a double caldera. Accessible only by weekly boat or helicopter, Aogashima offers solitude and starry skies like nowhere else in Japan. A trail leads to a geothermal sauna and steaming vents of the inner crater (Maruyama). Villagers farm salt and distilled shochu liquor from local sugarcane. The entire island feels like a secret—an off-the-grid paradise for adventurers willing to journey to the edge of civilization.', NULL, 0),

(332, 8, 35.70540, 139.64943, 'Tempura Tensuke', 'Suginami (Koenji), Tokyo, Japan', 'A 10-seat hole-in-the-wall tempura bar famed among locals for its signature “bomb” egg tempura—crispy outside with a molten yolk inside. Open since 1987, Tensuke has customers line up for its affordable, made-to-order tempura bowls. The jovial chef performs an egg-cracking show for each order. This no-frills gem has a cult following and even earned a Bib Gourmand mention, proving that incredible food can come from the humblest venues.', NULL, 0),

(333, 15, 35.69384, 139.70029, 'Omoide Yokocho', 'Shinjuku, Tokyo, Japan', 'A narrow alleyway by Shinjuku Station packed with over 60 tiny eateries and izakayas, many specializing in yakitori (grilled skewers) and ramen. Also nicknamed “Piss Alley” from its post-WWII origins, it retains a retro charm with paper lanterns, smokey grills, and cozy counters seating just a handful of patrons. Despite becoming more known to tourists, it still offers an authentic atmosphere of post-war Tokyo where salarymen and adventurous travelers squeeze in side by side for cheap drinks and delicious street food.', NULL, 0),

(334, 5, 35.65981, 139.70046, 'Nonbei Yokocho', 'Shibuya, Tokyo, Japan', 'Tucked next to Shibuya’s neon chaos, this tiny alley from the 1950s harbors around 30 micro-bars, each with only 5–8 seats. Behind old wooden doors, proprietors serve up beer, sake, and home-style snacks in an intimate setting where strangers inevitably chat elbow-to-elbow. The alley’s nostalgic charm (lantern-lit, under tangled overhead wires) makes it a treasured refuge of old Tokyo nightlife, immune to surrounding modernization. It’s an ideal spot to experience the friendly, low-key vibe of a bygone era over a drink or two.', NULL, 0),

(335, 12, 35.70330, 139.57884, 'Harmonica Yokocho', 'Kichijoji, Tokyo, Japan', 'A maze of over 100 tiny stalls and bars near Kichijōji Station, originally a post-war black market. By day, vendors sell clothing, spices, and sundries in corridors so narrow they resemble a harmonica’s holes (hence the name). By night, the shutters lift on snug standing bars and bistros offering craft cocktails, yakitori, or gyoza. With its hip yet retro vibe, Harmonica Yokocho draws in local creatives and students. It’s one of the city’s best-kept secrets for an evening of bar-hopping among lantern-lit alleys with a touch of Showa era nostalgia.', NULL, 0),

(336, 46, 35.72847, 139.77070, 'Yanaka Ginza', 'Taito (Yanaka), Tokyo, Japan', 'A charming old-style shopping street in a historic neighborhood that survived war and modernization. Lined with about 70 small family-run shops selling street foods (like croquettes and dumplings), crafts, and household goods, Yanaka Ginza retains an atmosphere of Tokyo’s 1950s “shitamachi” working-class era. Stray cats often wander the lanes, and cat-themed souvenirs abound (the area is sometimes called Cat Town). At dusk, locals gather on the famous Yuyake Dandan steps to watch the sunset over the quaint rooftops, wrapping up another day in this living museum of everyday Tokyo life.', NULL, 0),

(337, 8, 34.66994, 135.50223, 'Hozenji Yokocho', 'Osaka, Osaka Prefecture, Japan', 'A short stone-paved alley in Osaka’s Dotombori area that feels worlds apart from the neon around it. Flanked by traditional restaurants and izakayas, Hozenji Yokocho exudes a peaceful Edo-period charm, lit by lanterns and the glow of the tiny moss-covered Hōzen-ji temple where visitors splash water on Fudō-myōō’s statue for luck. It’s an ideal spot to try Osaka specialties (like kusikatsu skewers or okonomiyaki) in an intimate setting. Many establishments are long-running and family-owned, preserving the culinary soul of old Osaka.', NULL, 0),

(338, 12, 34.39289, 132.45937, 'Okonomimura', 'Naka-ku, Hiroshima City, Japan', 'A four-story building in downtown Hiroshima dedicated entirely to okonomiyaki—specifically Hiroshima-style okonomiyaki, which layers cabbage, noodles, batter, and sauce. Okonomimura (“Okonomiyaki Village”) houses over 20 small vendor stalls, each with a griddle counter where chefs cook the savory pancakes to order. Diners squeeze in and often chat with the chef as they watch their meal assembled. Each stall has its own variation or secret sauce, inviting repeat visits to compare. It’s a one-stop destination to experience Hiroshima’s beloved soul food among locals in a lively, no-frills atmosphere.', NULL, 0),

(339, 46, 33.59035, 130.40172, 'Fukuoka Yatai Stalls', 'Tenjin & Nakasu, Fukuoka, Japan', 'Dozens of open-air food stalls pop up on Fukuoka’s streets each evening, creating an inviting nightlife scene unique to the city. Each yatai is essentially a small mobile kitchen with a few stools, serving hearty treats like Hakata ramen, yakitori, tempura, or oden hotpot. Popular clusters can be found around Nakasu Island and Tenjin. Locals and tourists cram together under the tented roofs, sharing conversation over simple, delicious dishes and drinks. It’s an informal, communal way to dine and a must-do for experiencing Fukuoka’s friendly food culture.', NULL, 0),

(340, 12, 35.17091, 136.88494, 'Yanagibashi Central Market', 'Nagoya, Aichi Prefecture, Japan', 'A venerable fish market in Nagoya operating for over a century. Every morning, the market buzzes as wholesalers and local shoppers haggle over fresh seafood and produce. By 9–10 AM, some stalls transform into tiny eateries serving ultra-fresh sushi, kaisendon (seafood bowls), or grilled eel to the public. The atmosphere is authentic and slightly gritty, with narrow aisles and the sing-song calls of vendors. Far less touristy than Tokyo’s famous markets, Yanagibashi offers a slice of everyday Nagoya life and a chance to taste its ocean bounty at local prices.', NULL, 0),

(341, 5, 36.57086, 136.65658, 'Ōmichō Market', 'Kanazawa, Ishikawa Prefecture, Japan', 'Kanazawa’s main fresh market since the Edo period, known as “Kanazawa’s Kitchen.” Under one roof, nearly 200 stalls sell everything from snow crab, sweet shrimp, and yellowtail to Kaga vegetables and locally brewed sake. In recent years, trendy kaisendon restaurants within the market have drawn domestic tourists, but it still retains local flair: vendors shouting Kanazawa dialect and elderly shoppers pulling carts. Visitors can slurp down oysters at a sidewalk stand or enjoy a bargain seafood bowl topped with the morning’s catch. It’s a must-visit to appreciate Hokuriku’s rich food culture up close.', NULL, 0),

(342, 15, 36.14137, 137.25169, 'Takayama Old Town & Breweries', 'Takayama, Gifu Prefecture, Japan', 'In the Sanmachi historic district of Takayama, preserved Edo-period merchant streets are home to several centuries-old sake breweries. Look for sugidama (cedar balls) hung above shop entrances, signaling new sake is ready. Inside, you can sample fragrant junmai sake in tiny cups or buy bottles wrapped in brown paper. Alongside the breweries are craft shops and cafes occupying dark-wood townhouses. Though Takayama is on some tourist routes, it’s still quieter than Kyoto, and an early morning or late afternoon stroll with sake tasting feels pleasantly like stepping back in time among the alpine town’s charming streets.', NULL, 0),

(343, 46, 34.21374, 135.58528, 'Koyasan Temple Cuisine (Shojin Ryori)', 'Mount Kōya, Wakayama Prefecture, Japan', 'On the sacred Koyasan plateau, over 50 Buddhist temple lodgings (shukubō) offer an overnight experience that includes **shōjin ryōri**, the elaborate vegan cuisine of monks. Diners sit on tatami as course after course of beautifully presented dishes—seasonal mountain vegetables, tofu, sesame “tofu”, tempura, pickles, and miso soup—are served, all without meat, fish, garlic, or onion. The flavors are subtle and refined, intended to nourish body and spirit without inflaming passions. Eating this way in a tranquil temple setting, often by candlelight, is a meditative cultural journey into Japan’s spiritual heart.', NULL, 0),

(344, 8, 33.55875, 133.53110, 'Hirome Market', 'Kochi City, Kochi Prefecture, Japan', 'A lively indoor food market and beer hall beloved by locals. Hirome Market houses around 60 stalls offering diverse options: fresh katsuo no tataki (seared bonito) – Kochi’s specialty – grilled eel, Chinese dumplings, draft beers, and more. Customers carry their trays to communal tables in the center, leading to a convivial atmosphere where strangers chat freely (especially after a few local yuzu cocktails!). Open from morning till late, it’s a spot where salarymen, students, and tourists mingle, encapsulating Kōchi’s easygoing and welcoming spirit.', NULL, 0),

(345, 12, 26.21402, 127.68611, 'Makishi Public Market', 'Naha, Okinawa Prefecture, Japan', 'Called “the kitchen of Okinawa,” Makishi Market is a two-level arcade where locals buy tropical ingredients like goya (bitter melon), purple sweet potatoes, and fresh pork (every part of the pig from ears to feet). On the first floor, vendors also sell live seafood—buyers can even take a fresh fish upstairs to one of the small restaurants to have it cooked to order for lunch. The second-floor food stalls serve Okinawan classics like goya champuru, rafute (braised pork belly), and sea grape seaweed. Despite a recent rebuild, it remains delightfully chaotic and authentic, offering a crash course in the distinct cuisine of the Ryukyus.', NULL, 0),

(346, 15, 43.05525, 141.35384, 'Ganso Ramen Yokocho', 'Susukino, Sapporo, Hokkaido, Japan', 'Tucked in the Susukino nightlife district, this is the original “Ramen Alley” that birthed Sapporo’s miso ramen craze in the 1950s. The narrow lane hosts 17 tiny ramen shops, some operated by second-generation owners. Each shop has its variation of rich miso-based broth and butter-corn toppings that Hokkaidō ramen is famous for. Neon signs, noren curtains, and mouth-watering aroma fill the corridor. Tourists and locals alike squeeze in for a steaming bowl to cap off a night out, making it a flavorful slice of Sapporo’s food culture history.', NULL, 0),

(347, 46, 35.66042, 139.78109, 'Tsukishima Monja Street', 'Chuo (Tsukishima), Tokyo, Japan', 'A dedicated street in Tokyo’s Tsukishima district with over 70 restaurants specializing in monjayaki, a local downtown delicacy similar to okonomiyaki but with a runnier batter. Patrons sit around teppan grills, cooking the savory mixture of flour batter with cabbage, seafood, mochi, etc., then eating it straight off the grill with small spatulas. Monja Street’s eateries are mostly family-run and display a nostalgic Shōwa-era vibe. It’s an interactive dining experience that’s both delicious and fun, giving insight into Tokyo’s working-class comfort food culture (and a messy one at that!).', NULL, 0),

(348, 12, 33.59972, 131.18814, 'Nakatsu Karaage Street', 'Nakatsu, Oita Prefecture, Japan', 'The city of Nakatsu is famed for its **karaage** (Japanese-style fried chicken), boasting dozens of small, takeout-focused karaage joints per capita – many of them award-winners in national competitions. A self-guided “karaage map” leads hungry visitors to spots like Karafuku or Genkotsu-kun to sample crispy, juicy chicken thigh nuggets marinated in soy, garlic, and ginger. Each shop offers its own secret marinade recipe. The experience is essentially a fried chicken crawl: walking or driving from shop to shop, grabbing piping hot karaage in paper bags. It’s greasy, delightful, and a proud local tradition that puts this out-of-the-way city on Japan’s gourmet map.', NULL, 0),

(349, 5, 34.79261, 133.61731, 'Bitchū Matsuyama Castle', 'Takahashi, Okayama Prefecture, Japan', 'Japan’s only original castle keep built atop a mountain, often emerging above a sea of clouds on autumn mornings. A steep hike (or shuttle + short climb) through forest leads to this small 17th-century castle, perched 430m high. The reward is an exceptionally well-preserved fortress and panoramic views of the surrounding valley. Because of the effort required, visitors are few, lending an almost private discovery feel. The resident castle lord’s two cats sometimes greet guests. In cooler months under the right conditions, photographers flock to nearby viewpoints at dawn to capture the “castle in the sky” illusion as fog swirls below the ramparts.', NULL, 0),

(350, 8, 35.32301, 134.86306, 'Takeda Castle Ruins', 'Asago, Hyogo Prefecture, Japan', 'Atmospheric stone ruins of a 15th-century castle sprawled across a mountain ridge 353m high. Nicknamed “Japan’s Machu Picchu,” the site is famed for its ethereal appearance floating in a morning sea of clouds during autumn. Visitors who hike up in early hours (or take a seasonal shuttle partway) can wander the massive foundations and imagine the castle that once stood while gazing at peaks piercing fog below. By day, it offers unobstructed views of the countryside. There are no buildings left, but the sprawling layout of mossy stone walls and terraces conjures a romantic sense of faded glory, especially when mist envelops the mountaintop.', NULL, 0),

(351, 12, 37.12427, 138.52956, 'Hoshitoge Rice Terraces', 'Tōkamachi, Niigata Prefecture, Japan', 'Hundreds of small rice paddies layered on a steep hillside, creating a patchwork of mirrors reflecting the sky. At dawn on humid summer days, a sea of mist often drifts through the valley, producing a dreamlike scene highly prized by photographers. In winter the fields lie under deep snow, and in spring they fill with water catching sunrise and stars (Hoshitoge means “stars pass through”). With no tourist infrastructure aside from a small parking lookout, these terraces remain a peaceful testament to the harmony of agriculture and mountain landscape in Niigata’s countryside.', , 0),

(352, 46, 34.42065, 131.06321, 'Motonosumi Inari Shrine', 'Nagato, Yamaguchi Prefecture, Japan', 'A striking seaside shrine famed for 123 vermilion torii gates that wind down a cliffside to the Sea of Japan. This picturesque tunnel of gates, built in 1955 at the behest of a fox spirit (legend says), contrasts brilliantly with the blue ocean and sky. At the cliff’s base, waves crash against rocks, and an optional donation box sits atop a gate (visitors try to throw coins into it for good luck). With no public transport directly here, it sees fewer crowds than more accessible shrines, offering a serene and photogenic spiritual spot off the typical path.', , 0),

(353, 23, 35.57035, 135.19517, 'Amanohashidate Sandbar', 'Miyazu, Kyoto Prefecture, Japan', 'Ranked among Japan’s “Three Scenic Views” for centuries, Amanohashidate is a natural sandbar covered in pine trees that bridges two sides of Miyazu Bay. Its name means “Bridge to Heaven”; tradition says to view it by bending over and looking upside-down between your legs, making the landstrip appear to float in the sky. Visitors can walk (~3.6km) or cycle across the pine-lined path, enjoying beaches on either side. Viewpoints on mountains at either end provide the classic postcard perspectives of this breathtaking geological curiosity that has inspired poets and emperors alike.', NULL, 0),

(354, 5, 38.01827, 138.36530, 'Sado Island', 'Sado City, Niigata Prefecture, Japan', 'A large, historically rich island once used for exiles, now a hidden gem with rugged coasts, rice terraces, and a thriving traditional culture. Visitors can explore the old gold mine tunnels of Aikawa, ride a tarai-bune (tub boat) with fisherwomen in the Ogi area, or attend the internationally renowned Earth Celebration festival by Kodo taiko drummers. The island’s landscapes range from the dramatic cliffs of Sotokaifu Coast to peaceful persimmon-dotted villages. With limited public transport, renting a car or bike is best to discover Sado’s slow pace and well-preserved way of life.', NULL, 0),

(355, 46, 33.77011, 135.77852, 'Kawayu Onsen Sennin-buro', 'Hongu, Wakayama Prefecture, Japan', 'Each winter, a section of the Oto River in Kawayu Onsen is dammed to create a vast open-air hot spring bath, nicknamed the “Thousand-person Bath.” Geothermal hot water bubbles up through the sandy riverbank, mixing with the river’s cold flow to form a natural outdoor spa. Bathers of all ages soak together under the sky (wearing swimsuits), surrounded by rocks and sometimes falling snow. In other seasons, visitors can still dig their own personal hot spring pools in the gravel. Part of the Kumano Kodo area, the sennin-buro is a unique example of people communing with nature’s warmth.', NULL, 0),

(356, 8, 33.85536, 134.01839, 'Nagoro Doll Village', 'Nagoro, Tokushima Prefecture, Japan', 'A tiny nearly-abandoned hamlet in the Iya Valley where life-size dolls outnumber the living 10:1. As residents passed away or moved, local artist Ayano Tsukimi began creating cloth effigies in their likeness. Now around 350 dolls “inhabit” the village: fishermen sitting by the river, students filling an old classroom, grandmothers resting on benches. Walking through Nagoro is eerie yet whimsical—a commentary on rural depopulation turned folk art installation. Though remote, those who venture here find a touching and haunting scene of a village populated mainly by memories.', NULL, 0),

(357, 12, 37.15688, 139.73797, 'Ōuchijuku', 'Shimogō, Fukushima Prefecture, Japan', 'A preserved Edo-period post town consisting of some 30 thatched-roof houses lining an unpaved street, once an important stop on the Aizu–Nikkō trade route. With telephone poles buried underground to maintain authenticity, Ōuchijuku instantly transports visitors to the 17th century. Shops sell handmade crafts and local specialties like **negi soba** (buckwheat noodles eaten with a long green onion in lieu of chopsticks). In winter, heavy snow on the thatch creates a picturesque scene often illuminated by night festivals. It’s a charming detour into old Japan, far from modern city life.', NULL, 0),

(358, 15, 31.36150, 130.43283, 'Chiran Samurai District', 'Chiran (Minamikyūshū), Kagoshima, Japan', 'A quiet street preserving seven Edo-era samurai residences and their exquisite gardens behind earthen walls and neatly trimmed hedges. Unlike bustling Kyoto, Chiran’s samurai quarter sees few visitors, allowing for leisurely strolling or cycling. Each estate features a small landscaped garden—some with serene ponds, others with carefully placed stones and karikomi topiaries—viewable from tatami-mat rooms. The town is also known for its WWII kamikaze history (with a Peace Museum nearby), but the samurai district offers a peaceful glimpse into aristocratic rural life of the 18th century.', NULL, 0),

(359, 23, 31.58500, 130.60605, 'Sakurajima Lava Trail', 'Sakurajima (Kagoshima), Kagoshima, Japan', 'An opportunity to hike on an active volcano! Sakurajima, the smoking cone in Kagoshima Bay, has several short “lava promenade” trails winding through black volcanic rock fields created by past eruptions. The 3km Nagisa Lava Trail is the most popular: it passes bizarrely shaped lava formations now colonized by pine trees and provides close views of the simmering peak (which often emits ash clouds). Along the way, free foot-bath hot springs let you soak your feet in geothermally heated water while gazing at the volcano. It’s a stark, lunar-like landscape combined with subtropical greenery – a fascinating study in nature’s resilience.', NULL, 0),

(360, 46, 35.53900, 134.22912, 'Tottori Sand Dunes', 'Tottori, Tottori Prefecture, Japan', 'Towering sand hills along the Sea of Japan coast that make up Japan’s largest dune field (16 km²). Winds continuously reshape the dunes, some up to 50 meters high, creating rippling patterns like a mini-Sahara. Visitors can ride camels in tourist season, try sandboarding down the slopes, or trek to the Oasis (an occasional pond appearing among the dunes). The view from the highest ridge offers a panorama of golden sand meeting blue sea. Despite being Tottori’s top attraction, the vast area means one can still find solitary spots to channel Lawrence of Arabia vibes. Nearby, the Sand Museum showcases intricate sand sculptures, but it’s the raw dunes that truly captivate.', NULL, 0),

(361, 5, 35.12306, 132.46314, 'Iwami Ginzan Silver Mine', 'Ōda, Shimane Prefecture, Japan', 'A UNESCO World Heritage site featuring the eerie remnants of what was once one of the world’s richest silver mines, active 16th–19th centuries. Today, a few unlit mine shafts (like Ryugenji-mabu) can be walked through with helmets and flashlights, revealing pickaxe marks and dripping spring water. The surrounding hills have lush walking trails passing mossy stone ruins of refineries and guardhouses. At the foot of the mountains lies Omori, a charming village of traditional buildings and samurai residences now repurposed as cafes and shops. Far off the beaten path, Iwami Ginzan offers a tangible sense of history entwined with nature’s quiet reclamation.', NULL, 0),

(362, 12, 34.40829, 133.20430, 'Onomichi Temple Walk', 'Onomichi, Hiroshima Prefecture, Japan', 'A scenic hillside path weaving through the quaint seaside town of Onomichi, connecting 25 small temples via narrow alleys and stone staircases. Along the route, one encounters whimsical sights like “Manekineko Museum” and many friendly cats lounging about (Onomichi is sometimes called a “city of cats”). Highlights include Senkōji Temple with its panoramic lookout and the literary stone monuments dotted along the way, as famous Japanese writers loved Onomichi. The pace is slow and reflective, offering travelers a peaceful blend of cultural exploration and Seto Inland Sea views far from big city crowds.', NULL, 0),

(363, 46, 34.59658, 133.77166, 'Kurashiki Bikan Quarter', 'Kurashiki, Okayama Prefecture, Japan', 'A beautifully preserved canal district showcasing white-walled, black-tiled **kura** storehouses from the 18th century, when Kurashiki thrived as a rice trade center. Weeping willows line the canal, and small boats offer rides that glide under stone bridges. Many old buildings are now museums (like the Ohara Museum of Art with its impressionist collection) or charming cafes and boutiques. In the evening, gas lantern-style lights reflect on the water, evoking a romantic atmosphere. Despite its picture-postcard looks, Kurashiki remains a living neighborhood, where one can savor local specialties like denim-blue soft serve ice cream (a nod to the region’s textile industry) while strolling the alleys of a bygone era.', NULL, 0),

(364, 15, 34.19427, 133.80701, 'Kanamaruza Kabuki Theater', 'Kotohira, Kagawa Prefecture, Japan', 'Japan’s oldest surviving wooden kabuki playhouse, built in 1835, offering an authentic glimpse into Edo-period entertainment. Still operational for seasonal performances, the theater retains original features: low wooden benches, a rotating “seriadashi” stage floor, and even hidden trapdoors. When no shows are on, visitors can tour backstage, seeing the old-fashioned stage mechanisms and trying the customer boxes. The dim lighting, creaking floorboards, and lingering scent of wood and history make it easy to imagine a time when locals packed the house to see kabuki stars. During the spring Grand Kabuki performance, the tiny town comes alive as top actors grace this rural stage, a testament to the enduring allure of traditional performing arts.', NULL, 0),

(365, 5, 38.15400, 140.41269, 'Zao “Snow Monsters”', 'Zao Onsen, Yamagata Prefecture, Japan', 'High on the slopes of Mt. Zao, frost and wind transform the alpine fir trees into giant, grotesque shapes locally called **juhyō** or “snow monsters.” Each winter, thousands of these snow/ice encrusted trees stand like an army of white beasts on the mountainside. A ropeway carries visitors to a summit viewpoint and a lit-up night walk among the illuminated monsters is a popular event in peak season (February). By day, skiers slalom through them on Zao’s ski courses. It’s an awe-inspiring natural phenomenon that feels like wandering through a surreal frozen forest of creatures. (The effect disappears in spring as the ice melts.)', NULL, 0),

(366, 12, 43.06059, 142.60432, 'Tomamu Unkai Terrace', 'Shimukappu, Hokkaido, Japan', 'Located at 1,088m on Mount Tomamu, this sky-deck is designed for viewing **unkai** – the “sea of clouds” phenomenon. At dawn on select summer mornings, thick clouds fill the valley below while the mountaintop stays clear, giving the illusion of an endless white ocean. The resort runs an early gondola so guests can reach the terrace by sunrise. There are cloud-themed hammocks, a café, and even a dramatic Cloud Walk platform extending out above the mist. It’s a rare meteorological spectacle that, when conditions cooperate, delivers an ethereal experience of literally floating above the clouds (complete with occasional sun peeking over, painting the cloud tops orange and pink).', NULL, 0),

(367, 46, 31.56840, 131.42333, 'Udo Jingū Shrine', 'Nichinan, Miyazaki Prefecture, Japan', 'A unique seaside Shintō shrine built into a sea-cave on the side of a cliff. After descending a winding path along the ocean (with stunning coastal views of waves crashing against rock formations), visitors enter the cavern where a colorful shrine dedicated to the mother of Japan’s first emperor is nestled. The shrine is known for bringing luck in marriage and childbirth; people purchase small clay balls and toss them at a target rock (“Breast Rock”) on the ocean side – landing one in the hole is said to grant wishes. The combination of vermilion torii, turquoise waters, and the dim cave interior underlines Udo Jingū’s almost mystical ambiance.', NULL, 0),

(368, 8, 32.62778, 129.73858, 'Hashima (Gunkanjima)', 'Nagasaki, Nagasaki Prefecture, Japan', 'A tiny abandoned island off Nagasaki, once the most densely populated place on Earth, now a ghost town of crumbling concrete. nicknamed “Battleship Island” for its shape, Hashima was a coal mining colony from 1887–1974. At its peak, over 5,000 people lived on this windswept rock, in high-rise apartments tightly packed between mine shafts. After the mine closed, everyone left abruptly, leaving behind an apocalyptic landscape frozen in time. Today, guided boat tours allow brief landings onto a stabilized viewing area of the island’s eerie ruins (weather permitting). It’s an unsettling yet fascinating monument to industrial rise and fall, and a filming location for movies like *Skyfall*.', NULL, 0),

(369, 12, 41.27611, 141.13750, 'Mount Osore (Osorezan)', 'Mutsu, Aomori Prefecture, Japan', 'Literally “Fear Mountain,” Osorezan is a volcanic caldera regarded in Japanese folk belief as an entrance to the afterlife. A desolate, otherworldly landscape greets visitors: gray sands, bubbling sulfur pits, and a brightly colored acidic lake shore strewn with stones and Jizō statues (bodhisattvas for deceased children). Small pinwheels and toys left in memory of lost children spin in the barren breeze, adding to the eerie atmosphere. In summer, mediums (itako) gather here for the Bodaiji Temple’s festival to channel messages from the dead. Despite (or because of) its bleakness, Osorezan is powerfully spiritual – a place to contemplate death and rebirth in the raw geothermal earth.', NULL, 0),

(370, 46, 39.59361, 140.56951, 'Kakunodate Samurai District', 'Senboku, Akita Prefecture, Japan', 'Often called “Little Kyoto of Tōhoku,” Kakunodate is a former castle town famed for one of the best-preserved samurai neighborhoods in Japan. Dozens of wooden samurai mansions sit along wide, cherry tree-lined lanes. Some estates (e.g., Aoyagi and Ishiguro houses) are open as museums, displaying armor, calligraphy, and lifestyle artifacts of the samurai class. In late April, drooping cherry blossoms create pink tunnels over the black board fences – a breathtaking sight drawing visitors from afar. Even so, the town remains quiet, especially in the off-season, allowing one to stroll leisurely and absorb the historical ambiance. Combined with an adjoining merchant district, Kakunodate offers a step back into the Edo era against a rural backdrop.', NULL, 0),

(371, 5, 39.33194, 141.54075, 'Tōno Furusato Folk Village', 'Tōno, Iwate Prefecture, Japan', 'An open-air museum in the countryside of Tōno, celebrated as the heartland of Japanese folklore (home of kappa water spirits and other legends). The village features traditional *magariya* L-shaped farmhouses with thatched roofs, once typical in this region. Visitors can enter these houses to see hearths, farm tools, and sometimes local artisans demonstrating crafts. The surrounding gardens have streams and olden scarecrows, evoking scenes from the classic *Tōno Monogatari* tales. Nearby, one can visit real sites from those legends: a shrine to the mischievous **zashiki-warashi** spirit, or Kappabuchi pool where cucumber-loving kappa supposedly lurk. It’s a charming destination for those interested in rural life and myth in Japan’s “City of Folklore.”', NULL, 0),

(372, 15, 39.84656, 141.61547, 'Ryūsendo Cave', 'Iwaizumi, Iwate Prefecture, Japan', 'One of Japan’s three great limestone caves, Ryūsendo extends over 5 km (with about 700m open to public). Inside, visitors walk past fantastical stalactites and through cathedral-like caverns down to a series of underground lakes so clear and blue they seem illuminated. In fact, one lake is over 120m deep – one of the world’s deepest subterranean lakes – and is lit for dramatic effect. Bats flit in the upper chambers (it’s a designated Natural Monument for them). The cave stays a cool 10°C year-round. A recent discovery opened a new route, adding more waterfalls and emerald pools to marvel at. Emerging from the cave, you’re greeted by dense forest and a gushing spring – it’s easy to see how Ryūsendo earned its name “Cave of the Dragon’s Spring.”', NULL, 0),

(373, 23, 36.41419, 136.90816, 'Ainokura Gasshō Village', 'Nanto (Ainokura), Toyama Prefecture, Japan', 'A secluded mountain village of 20 gasshō-zukuri farmhouses, recognized as a UNESCO World Heritage Site along with more famous Shirakawa-gō, but far less visited due to its remote location. The thatched rooftops, pitched steeply to shed snow, resemble hands in prayer (*gasshō*). Ainokura is still a living community – locals cultivate mulberry and keep silkworm traditions alive. A small folk museum and a washi paper workshop welcome curious travelers. At night, the village is often illuminated softly, the only sounds the river and insects. In winter, deep snow and lights make it a fairy-tale scene. Visiting Ainokura feels like stepping into an Edo-period snow globe, where time slows among the timeless farmsteads.', NULL, 0),

(374, 8, 36.20350, 136.11972, 'Tōjinbō Cliffs', 'Sakai, Fukui Prefecture, Japan', 'A stretch of rugged basalt coastline featuring towering hexagonal rock columns eroded by the Sea of Japan waves. These stark 25m-high cliffs, formed 12 million years ago, have a somber beauty and are associated with local legends (named after a rogue monk Tōjinbō who, as one story goes, was thrown off the cliffs). Visitors can walk along the top for dramatic ocean vistas or take a boat ride to see the cliff faces and sea caves from below. The waves crash with incredible force on windy days, sending spray over the precipice. While the area is infamously known in Japan for suicides, recent efforts have stationed volunteers to patrol and help – adding a human touch of compassion to this natural wonder. Many simply enjoy the windswept scenery and local seafood stalls (try rock oyster curry) at this powerful meeting of land and sea.', NULL, 0),

(375, 15, 36.14460, 136.32136, 'Eihei-ji Temple', 'Eiheiji (Fukui City), Fukui Prefecture, Japan', 'A serene Zen Buddhist monastery founded in 1244 by Dōgen, nestled in old-growth cedars. Eiheiji (“Temple of Eternal Peace”) is still an active training center for Sōtō Zen monks. Visitors can quietly walk through wooden halls via creaking corridors, observing monks in meditation or tending chores as part of their practice. Highlights include the ornate Dharma Hall and a picturesque covered walkway of 250 stairs leading to the mausoleum. The atmosphere is hushed and contemplative – no tourist chatter, just the sound of sandals on wood and maybe distant sutra chanting. It’s possible to stay overnight as a lay trainee, participating in zen meditation and vegetarian meals. For a short visit or a spiritual retreat, Eiheiji offers a rare window into disciplined monastic life in a beautiful, forested setting.', NULL, 0),

(376, 5, 36.56118, 136.64634, 'Myōryū-ji (Ninja Temple)', 'Kanazawa, Ishikawa Prefecture, Japan', 'A clever Edo-period temple full of secret defenses and trap-like architecture – earning it the nickname “Ninja Temple” (though no actual ninja history). From the outside it appears two-story, but it conceals seven interior levels. During a guided tour (required), you’ll be shown hidden staircases, seppuku escape tunnels, trick doors, and a secrete lookout used to guard against intruders. The tour is only in Japanese (with basic English handouts), but the surprises are visible and fascinating in any language. Built by the Maeda lords under strict Tokugawa rules (which forbade fortresses), Myōryū-ji served as a disguised stronghold for refuge or defense. It’s a fun and intriguing stop that shows the ingenuity of feudal era design beyond the usual castles and gardens.', NULL, 0),

(377, 12, 37.43814, 137.24775, 'Shiroyone “Senmaida” Rice Terraces', 'Wajima, Ishikawa Prefecture, Japan', 'Literally “1000 rice paddies of Shiroyone,” these 1,004 tiny terraced fields cascade down a steep seaside slope along the Noto Peninsula coast. Though small and non-mechanized, they are still cultivated by hand, creating a stunning mosaic of green (in summer) or flooded mirrors (in spring) with the blue ocean as backdrop. At sunset the view is magical, and from October to March, thousands of LED lights illuminate each terrace in a popular nightly event, resembling a field of stars. An onsite shop offers local salt and rice products. Senmaida, now a Globally Important Agricultural Heritage site, exemplifies the harmony of human agriculture and natural topography in one breathtaking panorama.', NULL, 0),

(378, 46, 35.27319, 136.02047, 'Shirahige Shrine', 'Takashima, Shiga Prefecture, Japan', 'A Shinto shrine on the western bank of Lake Biwa, known for its striking red torii gate standing offshore in the lake’s shallow waters—often compared to Hiroshima’s famous Itsukushima Shrine gate, but with a fraction of the visitors. “Shirahige” means white beard, a reference to the long life deity worshiped here. It’s especially photogenic at sunrise, when the sun emerges between the torii pillars, or in the evening golden hour. Worshippers come to pray for longevity and matchmaking. The shrine grounds on land are quiet and ancient-feeling, with mossy lanterns and tall trees, but the highlight is that solitary gate in Japan’s largest lake, symbolizing a gateway between the mortal realm and the divine across the water.', NULL, 0),

(379, 12, 36.75998, 138.05524, 'Togakushi Shrine (Okusha)', 'Nagano, Nagano Prefecture, Japan', 'Hidden deep within cedar forests of Mount Togakushi, this shrine’s upper sanctuary (Okusha) is reached by a spectacular approach: a 2km walk through an avenue of 400-year-old giant cedars flanking a straight path. The atmosphere is hushed and sacred as sunlight filters through the dense canopy onto the mossy ground. The trail passes under several torii gates and by a thatched Zuijinmon gate guarding the final ascent. At trail’s end stands the modest Okusha shrine, dedicated to a deity of wisdom and said to mark where a rock door to the heavenly cave landed in myth. The Togakushi area is also famed for soba noodles and ninja legends (there’s a small Ninja Museum lower down). But making the pilgrimage to Okusha, especially in the early morning mist or light winter snow, is a spiritual journey into old Japan’s reverence for nature.', NULL, 0),

(380, 8, 35.97552, 137.78174, 'Narai-juku', 'Shiojiri (Narai), Nagano Prefecture, Japan', 'A beautifully preserved post town on the Nakasendō, which was the old highway linking Edo and Kyoto. Sometimes called “Narai of a Million People” for having been the area’s most prosperous stop, today it’s a quiet 1km stretch of classic wooden **machiya** houses with latticed windows, many of which have been in the same families for generations. Unlike the more visited Magome or Tsumago, Narai sees fewer tourists, so one can wander under the eaves, browse lacquerware shops (the town’s specialty), and even stay at a traditional inn that has hosted travelers for centuries. Without telephone poles or modern intrusions in sight, Narai-juku feels like a time-slip to the samurai era, especially in the soft light of late afternoon when day-trippers have gone.', NULL, 0),

(381, 15, 35.26819, 135.46710, 'Miyama Kayabuki-no-Sato', 'Nantan (Miyama), Kyoto Prefecture, Japan', 'A rural hamlet in the mountains north of Kyoto where over 30 traditional thatched-roof farmhouses form a living village (people actually reside in them, farming and crafting as they have for centuries). Unlike touristy folk parks, Miyama’s thatched homes are not exhibits but real homes, though a few function as minshuku (guesthouses) or cafes for visitors. There’s a small museum detailing thatching techniques and fire protection, as the community still gathers for roof repairs in a time-honored cooperative method. Surrounded by rice fields, vegetable plots, and forested hills, the village is idyllic in every season: lush green in summer, vivid colors in fall, and often snow-cloaked in winter. Visiting gives a rare glimpse into authentic countryside life in harmony with traditional architecture and nature.', NULL, 0),

(382, 46, 34.83637, 135.47014, 'Minoo Park & Waterfall', 'Minoh (Minoo), Osaka Prefecture, Japan', 'A peaceful forested valley just north of Osaka City, known for its easily accessible 33m waterfall and autumn maple leaves. A paved gentle trail (about 3km) follows the Minoo River, passing a few temples and shops (selling treats like maple leaf tempura) as it winds upward. At trail’s end, Minoo Falls cascades into a rocky pool surrounded by lush greenery; on weekdays it’s often quiet enough to hear birds and the roar of the falls rather than city noise. Wild monkeys sometimes appear along the route. In November, the entire valley erupts in reds and oranges, making it one of Kansai’s favorite koyo (fall foliage) spots. It’s a refreshing nature escape that feels surprisingly remote despite being under an hour from bustling Umeda.', NULL, 0),

(383, 8, 34.70541, 135.24679, 'Nunobiki Falls', 'Kobe, Hyogo Prefecture, Japan', 'A set of four waterfalls hidden in the forests immediately behind Shin-Kobe Station, often called one of Japan’s “three greatest divine falls” for their historic renown. The name means “Cloth Falls,” as the water is said to flow like white cloth. A short but steep hike leads you to viewpoints: the most famous being Mentaki and Ontaki (43m high) which have inspired poets since the 8th century. Despite being within city limits, the area feels wild and tranquil. The hike can continue upward to the Nunobiki herb garden or the Rokko mountain range, but many just enjoy the cool spray and sylvan setting of the falls as a quick nature getaway from the city. It’s particularly lovely in summer for beating the heat, and in autumn when maple leaves frame the cascades.', NULL, 0),

(384, 12, 35.62847, 134.80632, 'Kinosaki Onsen', 'Toyooka (Kinosaki), Hyogo Prefecture, Japan', 'A picturesque onsen town along a willow-lined canal near the Japan Sea coast, famous for its seven public hot spring baths. Guests strolling the streets in yukata and geta sandals, hopping from bath to bath, are a common sight. Each onsen has its own style and benefits, from caves to open-air tubs. The town deliberately keeps a traditional atmosphere: wooden ryokan, gas lamp-style streetlights, no neon signs. Sustainable efforts include no plastic bags (visitors carry a straw or cloth bag for towels and clothes) and a locally managed wildlife sanctuary for storks. In the evening, the canal area is lit softly, and the clip-clop of sandals echoes as people enjoy onsen-hopping and local Tajima beef or crab cuisine. Kinosaki embodies a classic, slow-paced onsen experience focused on relaxation and local charm.', NULL, 0),

(385, 23, 34.20583, 135.89768, 'Dorogawa Onsen', 'Tenkawa, Nara Prefecture, Japan', 'A small hot spring village high in the mountains of Nara, historically a retreat for yamabushi mountain monks of Mt. Ōmine (nearby). As a result, Dorogawa has a serene, somewhat mystical vibe – no alcohol was traditionally served (though that’s relaxed now) and the waters are said to cleanse both body and spirit. Stone-paved streets are lined with ryokan sporting wooden architecture and hanging lanterns. The iron-rich thermal water feeds public baths and inns, best enjoyed after a day hiking sacred peaks or visiting the nearby Ryusenji temple cave. At night, the village is very quiet, illuminated by old-fashioned lamps and the glow from ryokan entrances. In summer, fireflies dance by the river. Visiting Dorogawa is like slipping into a timeless enclave of spiritual refreshment and untouched nature.', NULL, 0),

(386, 46, 34.51279, 135.94164, 'Hase-dera Temple', 'Sakurai, Nara Prefecture, Japan', 'A grand temple complex nicknamed the “Temple of Flowers” for its year-round blooms (plum, cherry, peony, hydrangea, autumn maple, etc.). Hasedera’s defining feature is a sprawling wooden main hall perched on a hillside, reached by ascending a long covered corridor of 399 steps. Pilgrims pray to the massive 10m tall wooden Kannon statue (with 11 faces) housed inside – one of the largest of its kind. The overlook balcony offers a scenic view of the valley and village below. Despite its beauty and importance (it’s been a pilgrimage site since the 8th century), Hasedera is relatively uncrowded, especially on weekdays, allowing visitors to slowly climb and soak in the atmosphere of old Nara. It’s particularly famous for its peony garden in late spring, and for a peaceful, contemplative mood that many better-known temples can no longer offer.', NULL, 0),

(387, 12, 35.15717, 139.83516, 'Mount Nokogiri & Nihon-ji', 'Kyonan, Chiba Prefecture, Japan', 'Rising along Tokyo Bay in southern Chiba, Mt. Nokogiri (literally “sawtooth mountain”) features dramatic stone quarry cliffs and one of Japan’s largest Buddha carvings. A hike or ropeway up leads to the **Jigoku Nozoki** (“Peering into Hell”) rock outcrop – a small viewing platform perched over a sheer drop, offering thrilling bay views. Scattered on the mountain are 1,500 hand-carved arhat statues (many decapitated by anti-Buddhist movements in the 19th century, lending an eerie feel) and the Nihon-ji Daibutsu, a 31m tall Buddha figure carved into the cliff – bigger than Kamakura’s. The mountaintop Nihon-ji temple itself is ancient and adds to the atmosphere. It’s an unusual mix of nature, history, and a bit of adrenaline, yet remains off most tourists’ radar due to Chiba’s lesser-known status.', NULL, 0),

(388, 8, 36.77250, 140.39706, 'Fukuroda Falls', 'Daigo, Ibaraki Prefecture, Japan', 'A spectacular tiered waterfall often cited among Japan’s top three. The Taki River cascades over four major drops, totaling 120m high, earning it the nickname “Yodo-no-taki” (Four-time Falls). A poet once said one must see it in each of the four seasons to appreciate it fully – and indeed, it’s beautiful year-round: surrounded by vivid greenery in spring, misty and thunderous in summer, framed by autumn reds, and sometimes completely frozen into a blue-tinged ice wall in winter (when ice climbers occasionally scale it). An easy tunnel walk (with an elevator) brings visitors to viewing platforms right in front of the falls, and a newer upper observation deck gives a panoramic look. Local vendors near the entrance sell shiitake skewers and apples, adding a taste of the region to the excursion. Despite its grandeur, Fukuroda’s remote location keeps visitor numbers moderate except on peak foliage weekends.', NULL, 0),

(389, 15, 35.97713, 140.22035, 'Ushiku Daibutsu', 'Ushiku, Ibaraki Prefecture, Japan', 'A colossal bronze statue of Amida Buddha standing 120m tall (including base), once the tallest statue in the world. Set in a spacious garden with seasonal flowers, the statue is so large that an elevator takes visitors up 85m to a viewing gallery in the Buddha’s chest. Inside the five-story structure are peaceful chambers for reflection and a small museum; one floor even contains 3,000 tiny golden Buddha statues in a darkened hall, while another allows peeking out through the giant statue’s chest window over the countryside. Outside, a petting zoo and flower fields (e.g., cosmos and peonies) make it a family-friendly stop. The sheer scale of Ushiku Daibutsu is humbling – to stand by its foot is to barely reach the toenail – and it serves as a modern place of Buddhist devotion as well as an engineering marvel off the usual tourist circuit.', NULL, 0),

(390, 8, 36.75068, 139.99422, 'Oya History Museum (Stone Quarry)', 'Utsunomiya (Ōya), Tochigi Prefecture, Japan', 'An enormous underground quarry space left behind from mining Oya stone (a soft volcanic tuff) that operated from 1919 to 1986. Now a museum, visitors descend into a cool, cavernous world of cathedral-sized chambers with 30m-high walls, illuminated by soft lights. Exhibits of old mining equipment and photos line some carved halls. The vast scale, silence, and dim lighting give it a surreal atmosphere – it’s been used as a location for movies, music videos, and even wine aging. Above ground, one can also see the subtler remnants of Ōya’s stone heritage: the picturesque Ōya-ji Temple is partially carved into a cliff, and a towering Peace Kannon statue stands guard outside. Together, they tell the story of a town built from and by its distinctive stone, now peacefully retired into art and history.', NULL, 0),

(391, 12, 36.10050, 139.11055, 'Nagatoro Gorge', 'Nagatoro, Saitama Prefecture, Japan', 'A scenic gorge along the Arakawa River known for its layered, pillow-shaped rock formations (Iwadatami Rocks) that line the banks. Traditional wooden flat-bottomed boats ply the river, guided by boatmen with poles who navigate gentle rapids and share local lore. In autumn, the surrounding forests explode in color, reflecting on the clear water. Visitors can also hike up to Hodosan Shrine or take a ropeway for a panoramic view of the Chichibu mountains. Nagatoro is popular with Tokyo day-trippers on weekends, yet still retains a sleepy charm. It’s also a noted **geopark** for its geological curiosities. Whether enjoyed via a leisurely boat ride or picnicking on the warm rock slabs by the water, Nagatoro offers a refreshing taste of nature and tradition not far from the metropolis.', NULL, 0),

(392, 5, 36.49122, 138.93349, 'Ikaho Onsen (Stone Step Town)', 'Shibukawa, Gunma Prefecture, Japan', 'A classic hot spring town built along 365 stone steps that lead up a slope, flanked by ryokan inns, little shops, and bathhouses. The rust-colored thermal water of Ikaho contains iron, giving the bathwater a unique reddish tint believed to alleviate ailments. Halfway up the stairs stands a traditional public bath (Ishidan no Yu), and at the top sits Ikaho Shrine, where hot spring steam drifts atmospherically among the trees. Along the steps, visitors snack on Ikaho’s famous onsen steamed buns or sip locally-brewed sake. In summer, a festival sees locals carry ornate palanquins down the steps; in autumn, maples around the town turn brilliant hues. This vertical layout and nostalgic mood make Ikaho distinct among onsen resorts, embodying a bygone era of leisurely travel. (Keep an eye out for the 1900s-founded shooting gallery on the steps, a rarity now.)', NULL, 0),

(393, 15, 36.80419, 139.11774, 'Takaragawa Onsen', 'Minakami, Gunma Prefecture, Japan', 'A riverside hot spring resort deep in the mountain forests that feels like a secret paradise. Takaragawa is famous for its massive open-air baths—four mixed-gender rotemburo that hug the river’s edge, surrounded by boulders and towering trees. In winter, bathers soak in steaming hot waters while snow piles high around, and the river flows with ice chunks; in autumn, colored leaves drift onto the surface. Accommodation is in a traditional inn with tatami rooms, but day visitors can also use the baths. The baths are clothing-optional (modest bath towels are allowed for mixed bathing, and a women-only area is also available). With its rustic bridges, secluded setting, and sheer scale of the pools, Takaragawa offers perhaps one of Japan’s most iconic onsen experiences amid nature’s grandeur.', NULL, 0),

(394, 8, 35.63193, 139.71633, 'Meguro Parasitological Museum', 'Meguro, Tokyo, Japan', 'The world’s only museum dedicated to parasites – a delightfully creepy and educational little institution. Tucked on two floors of an unassuming building in Tokyo, it displays over 300 specimens of parasites that infect animals and humans. Its star attraction is an 8.8-meter-long tapeworm that once lived inside a person (displayed along a rope of equal length). Visitors can also see preserved parasites extracted from dolphins, bears, fishes, etc., and learn about their complex life cycles via concise English/Japanese explanations. Entry is free, and there’s even quirky parasite-themed merch like t-shirts and keychains. It’s a bizarre yet fascinating offbeat stop that provides insight into a hidden world, leaving you equal parts grossed out and amazed at nature’s complexity.', NULL, 0),

(395, 12, 35.32453, 136.97328, 'Meiji Mura Museum', 'Inuyama, Aichi Prefecture, Japan', 'An expansive open-air architectural park preserving over 60 buildings from Japan’s Meiji era (1868-1912) and early 20th century – a period of rapid Westernization. Strolling through Meiji Mura is like walking through time: you can enter a convict brick church from Kyoto, the elegant lobby of Frank Lloyd Wright’s Imperial Hotel (relocated here in pieces after demolition), a Nihonbashi police box, a high school from Sapporo, and even Japan’s first cabaret. Many structures are furnished with period items, and working streetcars and buses ferry visitors around the scenic lakeside grounds. It’s both a fun day out – riding a steam locomotive or dressing in Victorian clothes (rentable) – and an invaluable preservation of Japan’s cultural transformation. A must for history and architecture buffs, yet interactive enough for families too.', NULL, 0),

(396, 8, 34.47388, 136.79689, 'Meoto Iwa (Wedded Rocks)', 'Futami (Ise), Mie Prefecture, Japan', 'Two sacred rocks off the Futami coast joined by a thick **shimenawa** straw rope, symbolizing the union of the creator deities Izanagi and Izanami. The larger rock (with a small torii on top) represents the husband, and the smaller the wife. It’s a popular spot for couples to visit, especially during summer solstice when the sun rises directly between the rocks and alignment with Mount Fuji can be seen on clear days. At low tide, one can walk close; at high tide, they’re partially submerged, creating a picturesque scene of the torii seemingly floating. Nearby Futami Okitama Shrine celebrates marriage and easy childbirth, with many frog statues (frogs are messengers of the sea deity). It’s a quick, charming stop near Ise that encapsulates Shinto’s nature reverence and symbolism of marital harmony.', NULL, 0),

(397, 12, 33.10828, 131.14859, 'Kurokawa Onsen', 'Minamioguni, Kumamoto Prefecture, Japan', 'A storybook hot spring village nestled in a wooded valley, known for its uniform dark-wood architecture and eco-friendly, intimate vibe. Kurokawa strictly controls development – no neon signs or modern concrete hotel blocks here – preserving the look of a bygone era. Over twenty ryokan are scattered along a bubbling river, each with its own rotenburo baths, many open to day-trippers via a handy onsen-hopping pass. As you wander in yukata and geta down leafy paths, you’ll find hidden outdoor baths by waterfalls, cave baths, and even a riverbed bath. At night, dim lanterns light the main street, and the smell of wood smoke from ryokan hearths wafts through the cool air. Kurokawa’s emphasis on harmony with nature and community (they jointly handle trash, branding, events) makes it a model of sustainable tourism and arguably one of Japan’s most charming onsen destinations.', NULL, 0),

(398, 8, 35.75101, 136.93907, 'Gujō Hachiman', 'Gujo, Gifu Prefecture, Japan', 'A small castle town in Gifu known for its pristine waterways and summer dance festival. Canals and springs crisscross the town, famously clean enough that colorful koi fish swim in the gutters and locals once used specific pools (still visible) for washing vegetables or laundry. The atmosphere is idyllic, with old houses and willow trees along the Yoshida River. Gujo is also home to the Gujo Odori, one of Japan’s largest Bon dances, where for 32 nights in summer (including all-night dances on certain days) people dance in a circle to traditional songs, a practice unbroken for over 400 years. Additionally, the town produces most of Japan’s sample food replicas – and you can even try making one at a workshop. Whether dancing under the stars or strolling past water mills and the sake brewery, Gujo Hachiman offers a peaceful immersion into local culture off the standard tourist track.', NULL, 0),

(399, 12, 33.10352, 130.11105, 'Yūtoku Inari Shrine', 'Kashima, Saga Prefecture, Japan', 'One of Japan’s three great Inari shrines, yet far less crowded than Fushimi Inari in Kyoto. Yutoku Inari’s main hall is built into a steep hillside on impressive wooden stilts, similar to Kiyomizu-dera. It’s painted vivid vermilion and overlooks a valley – climb the winding path and you’ll pass through dozens of red torii gates to reach the Okunoin at the summit, which grants a splendid view of the town and fields below. The shrine is dedicated to the fox kami of prosperity and is especially popular for prayers related to business and fortune. In spring, azaleas bloom across the grounds; in fall, the maples turn bright red around the shrine’s pond and bridge. Due to its somewhat remote location in Saga, it retains a tranquil, spiritual atmosphere where one can admire the architecture and nature in relative peace compared to its famous counterparts.', NULL, 0),

(400, 15, 36.76597, 137.06667, 'Toyama Bay Firefly Squid', 'Namerikawa, Toyama Prefecture, Japan', 'A natural nocturnal spectacle occurring from March to June off the coast of Toyama Bay: billions of **hotaru-ika** (firefly squid) surface and emit an eerie blue bioluminescent glow. The phenomenon is often seen when fishermen pull up their nets before dawn – the boat lights and waves disturb the squid, causing them to light up the water like a blue aurora. Enthusiastic travelers can pre-dawn join special sightseeing boats from Namerikawa to witness the sparkling sea first-hand (conditions permitting), or visit the dedicated Firefly Squid Museum that offers an early morning “light show” in a darkened pool. This rare concentration of glowing squid, which according to Atlas Obscura means no predators (like dolphins) around, makes Toyama Bay one of the few places in the world to reliably see such marine magic.', NULL, 0),

(401, 8, 32.72779, 133.02307, 'Cape Ashizuri', 'Tosashimizu, Kōchi Prefecture, Japan', 'The southernmost point of Shikoku, offering a sublime vista of the Pacific’s expanse from atop 80-meter granite cliffs crowned by a bright white lighthouse. Cape Ashizuri is known for intense ocean blues, the result of the Kuroshio Current, and for a 360° panorama where on a clear day one can see the curvature of the earth. The cape is part of Ashizuri-Uwakai National Park and is visited by pilgrims for the nearby Kongōfukuji Temple (Temple 38 of the Shikoku Pilgrimage). A circular walking path leads through subtropical flora (like banyan trees) to observation decks and monuments, including a famous statue of John Mung (a local who became one of the first Japanese to visit America in the 19th century). With very few visitors at any time, the cape often feels like the “ends of the earth,” a place of windswept contemplation where Japan truly meets the open ocean.', NULL, 0);

-- End of dataset: 100 unique off-the-beaten-path travel spots in Japan (with locations, descriptions, and additional info as requested).
